security:
    encoders:
        MailerBundle\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: MailerBundle:User
                property: name

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                target_path_parameter: email
            provider: db_provider

    access_control:
        - { path: ^/email, roles: ROLE_USER }